version: '3'


services:


  nats-server:
    image: nats:latest


  client-geteway:
    build: 
      context: ./GeteWay
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-455722/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NTAS_SERVERS=nats://nats-server:4222


  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-455722/image-registry/auth-ms
    environment:
      - PORT=3004
      - NTAS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  product-ms:
    build: 
      context: ./products-microservice
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-455722/image-registry/products-ms
    environment:
      - PORT=3000
      - NTAS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./OrderMicroservice
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-455722/image-registry/orders-ms
    environment:
      - PORT=3000
      - NTAS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

# # =================================
# # Payment Microservice
# # =================================
  payment-ms:
    build:
      context: ./payments-microservice
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-455722/image-registry/payment-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NTAS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINTSECRET=${STRIPE_ENDPOINTSECRET}
      