apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-455722/image-registry/client-gateway
        name: gateway-ms
        env:
        - name: PORT
          value: "3000"
        - name: NTAS_SERVERS
          value: "nats://nats"
        resources: {}
