apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payment-ms
  name: payment-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-ms
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-455722/image-registry/payment-ms
        name: payment-ms
        env:
        - name: PORT
          value: "3000"
        - name: NTAS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:3003/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:3003/payments/cancel"
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret
        - name: STRIPE_ENDPOINTSECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpointsecret

        resources: {}
status: {}
